POST {{server_url}}/api/user/auth/login
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}"
}
{{console.info(response.rawHeaders)}}

POST {{server_url}}/api/user/auth/signup
Content-Type: application/json


{
  "email": "ka@wi.ca",
  "username": "k",
  "password": "pass"
}