GET {{server_url}}/api/post/
Content-Type: application/json

POST {{server_url}}/api/post/
Content-Type: application/json
X-CSRFToken: {{csrf}}

{
    "title": "test",
    "status": "Seed",
    "summary": "testin things out",
    "category_id": 1,
    "slug": "test",
    "content": "hello this is a test"
}
// {{console.info(request)}}

PUT {{server_url}}/api/post/5
Contenet-Type: application/json
X-CSRFToken: {{csrf}}

{
    "title": "Brand New",
    "status": "Flower",
    "summary": "Making Waves!",
    "category_id": 1,
    "slug": "test",
    "content": "hello this is a test"
}

PUT {{server_url}}/api/post/5
Content-Type: application/json
X-CSRFToken: {{csrf}}

{
    "archived": false
}


DELETE {{server_url}}/api/post/5
Content-Type: application/json
X-CSRFToken: {{csrf}}
