GET {{server_url}}/api/post/
Content-Type: application/json

GET {{server_url}}/api/post/test
Content-Type: application/json

POST {{server_url}}/api/post/
Content-Type: application/json
X-CSRFToken: {{csrf}}

{
    "title": "",
    "status": "Seed",
    "summary": "testin things out",
    "category_id": 1,
    "slug": "Sane",
    "content": "hello this is a test",
    "category": "art"
}
// {{console.info(request)}}

PUT {{server_url}}/api/post/2
Contenet-Type: application/json
X-CSRFToken: {{csrf}}

{
    "title": "Brand New",
    "status": "Flower",
    "summary": "Making Waves!",
    "category_id": 1,
    "slug": "test_another",
    "content": "hello this is a test\n# Header1\n- bullet point\n\n`code`\n\n```python\ndef a()\n\n    update()\n```"
}

PUT {{server_url}}/api/post/1
Content-Type: application/json
X-CSRFToken: {{csrf}}

{
    "archived": false
}

PUT {{server_url}}/api/post/1
Content-Type: application/json
X-CSRFToken: {{csrf}}

{"status":"Flower","summary":"Making Waves!","content":"hello this is a test\n# Header1\n- bullet point\n\n`code`\nE\n```python\ndef a()\n\n    update()\n```"}

DELETE {{server_url}}/api/post/5
Content-Type: application/json
X-CSRFToken: {{csrf}}
